# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('attachment', models.FileField(blank=True, upload_to=b'blog/static/attachment/')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('category', models.CharField(blank=True, default=b'--', max_length=30)),
                ('photo', models.ImageField(blank=True, default=b'blog/static/photo/default.png', upload_to=b'blog/static/photo/')),
                ('information', models.TextField(blank=True)),
                ('project', models.TextField(blank=True)),
                ('patent', models.TextField(blank=True)),
                ('article', models.TextField(blank=True)),
                ('works', models.TextField(blank=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleCategory'),
        ),
    ]
