# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe5\xa7\x93\xe5\x90\x8d')),
                ('reg_year', models.IntegerField(verbose_name=b'\xe5\x85\xa5\xe5\xad\xa6\xe6\x97\xb6\xe9\x97\xb4')),
                ('status', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\xaf\x95\xe4\xb8\x9a')),
            ],
            options={
                'verbose_name': '\u7814\u7a76\u751f',
                'verbose_name_plural': '\u7814\u7a76\u751f',
            },
        ),
    ]
