# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_graduate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': '\u52a8\u6001', 'verbose_name_plural': '\u52a8\u6001'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '\u516c\u544a\u901a\u77e5', 'verbose_name_plural': '\u516c\u544a\u901a\u77e5'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='text',
            field=models.TextField(blank=True, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
