# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170527_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': '\u516c\u544a\u901a\u77e5', 'verbose_name_plural': '\u516c\u544a\u901a\u77e5'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '\u52a8\u6001', 'verbose_name_plural': '\u52a8\u6001'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='news',
            name='host',
        ),
        migrations.RemoveField(
            model_name='news',
            name='lec_time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='organizers',
        ),
        migrations.RemoveField(
            model_name='news',
            name='place',
        ),
        migrations.RemoveField(
            model_name='news',
            name='presenter_detail',
        ),
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, upload_to=b'blog/static/attachment/news/', verbose_name=b'\xe7\x9b\xb8\xe5\x85\xb3\xe9\x99\x84\xe4\xbb\xb6'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='host',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'\xe4\xb8\xbb\xe6\x8c\x81\xe4\xba\xba'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='lec_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'\xe4\xb8\xbb\xe8\xae\xb2\xe4\xba\xba'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='organizers',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'\xe4\xb8\xbb\xe5\x8a\x9e\xe5\x8d\x95\xe4\xbd\x8d'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='place',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'\xe5\x9c\xb0\xe7\x82\xb9'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='presenter_detail',
            field=models.TextField(blank=True, verbose_name=b'\xe4\xb8\xbb\xe8\xae\xb2\xe4\xba\xba\xe7\xae\x80\xe4\xbb\x8b'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(blank=True, verbose_name=b'\xe8\xaf\xa6\xe7\xbb\x86\xe5\x86\x85\xe5\xae\xb9'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x86\x85\xe5\xae\xb9'),
        ),
    ]
